# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:23
from __future__ import unicode_literals

from django.db import migrations


def create_initial_items(apps, schema_editor):
    Item = apps.get_model('catalog', 'Item')

    Item(name='Razer Kraken Mobile',
         description='iOS Compatible Portable Headset',
         price=89.99, brand='Razer').save()
    Item(name='Razer BlackWidow Ultimate',
         description='Water and Dust-Resistant Mechanical Keyboard',
         price=109.99, brand='Razer').save()
    Item(name='ASUS CERBERUS 3.5mm Circumaural Gaming Headset',
         description='Superb, distraction-free sound in every scenario',
         price=109.99, brand='Asus').save()
    Item(name='ROG Gladius',
         description='Ergonomic 6400dpi professional gaming mouse with customizable click resistance',
         price=59.99, brand='Asus').save()
    Item(name='Logitech G430',
         description='Surround sound gaming headset',
         price=79.99, brand='Logitech').save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
    ]
